/* Election Manual Assistant — search engine + UI
   Data comes from js/data.js (MANUAL_DATA), generated by build_index.py. */
"use strict";

/* ---------------- text processing (must mirror build_index.py) ---------------- */

function stem(w) {
  if (w.length > 4 && w.endsWith("ies")) return w.slice(0, -3) + "y";
  if (w.length > 4 && /(ses|xes|zes|ches|shes)$/.test(w)) return w.slice(0, -2);
  if (w.length > 3 && w.endsWith("s") && !w.endsWith("ss")) w = w.slice(0, -1);
  if (w.length > 5 && w.endsWith("ing")) w = w.slice(0, -3);
  else if (w.length > 4 && w.endsWith("ed")) w = w.slice(0, -2);
  return w;
}

const STOP = new Set([
  "a","an","the","to","do","i","if","of","in","on","for","and","or","is","are",
  "what","how","when","where","who","why","with","from","that","this","it","as",
  "be","by","at","my","me","we","you","your","our","doe","should","can","could",
  "would","will","have","ha","had","about","into","out","up","get","got","need",
  "show","someone","something",
]);

/* Domain synonym expansion — query-side only. Each key (stemmed form) maps to
   extra stemmed terms that are OR'd into the query. */
const SYNONYMS = {
  bmd: ["ballot", "marking", "device"],
  vac: ["voter", "authority", "card"],
  sdr: ["same", "day", "registration"],
  epollbook: ["pollbook"],
  scanner: ["scanning", "unit"],
  tabulator: ["scanning", "unit"],
  machine: ["scanning", "unit", "device"],
  epb: ["pollbook"],
  id: ["identification"],
  handicap: ["disability", "accessible"],
  handicapped: ["disability", "accessible"],
  wheelchair: ["accessible", "disability"],
  poll: ["polling"],
  polling: ["poll"],
  ruin: ["spoil"],
  mistake: ["spoil", "replacement"],
  messed: ["spoil", "replacement"],
  broken: ["broken", "damaged"],
  cop: ["police", "officer"],
  police: ["law", "enforcement"],
  media: ["media", "reporter"],
  reporter: ["media"],
  camera: ["photograph", "electronic"],
  phone: ["electronic", "device", "cell"],
  translator: ["language", "assistance", "interpreter"],
  interpreter: ["language", "assistance"],
  spanish: ["language", "assistance", "multilingual"],
  wrong: ["correct", "precinct"],
  picture: ["photograph", "media", "electronic"],
  photo: ["photograph", "media", "electronic"],
  video: ["photograph", "media", "electronic"],
  campaign: ["electioneering"],
  campaigning: ["electioneering"],
  fleeing: ["fleeing", "flee"],
};

function tokenizeQuery(q) {
  const raw = (q.toLowerCase().match(/[a-z0-9]+/g) || []).map(stem);
  const terms = new Set();
  for (const t of raw) {
    if (t.length < 2 || STOP.has(t)) continue;
    terms.add(t);
    const syn = SYNONYMS[t];
    if (syn) syn.forEach((s) => terms.add(stem(s)));
    // Compound splitting: "powerstrip" isn't in the manual, "power strip" is.
    if (!MANUAL_DATA.INDEX[t] && t.length >= 6) {
      for (let i = 3; i <= t.length - 3; i++) {
        const a = stem(t.slice(0, i));
        const b = stem(t.slice(i));
        if (MANUAL_DATA.INDEX[a] && MANUAL_DATA.INDEX[b]) {
          terms.add(a);
          terms.add(b);
          break;
        }
      }
    }
  }
  return [...terms];
}

/* ---------------- BM25 search ---------------- */

const K1 = 1.4, B = 0.6;

function search(query, limit = 8) {
  const D = MANUAL_DATA;
  const terms = tokenizeQuery(query);
  if (!terms.length) return { terms, results: [] };

  const scores = new Map(); // chunkIdx -> score
  const hits = new Map();   // chunkIdx -> matched term count
  for (const t of terms) {
    const postings = D.INDEX[t];
    if (!postings) continue;
    const idf = Math.log(1 + (D.N - postings.length + 0.5) / (postings.length + 0.5));
    for (const [idx, tf] of postings) {
      const dl = D.DOCLEN[idx];
      const s = idf * ((tf * (K1 + 1)) / (tf + K1 * (1 - B + B * (dl / D.AVGDL))));
      scores.set(idx, (scores.get(idx) || 0) + s);
      hits.set(idx, (hits.get(idx) || 0) + 1);
    }
  }

  // Coverage bonus: chunks matching more distinct query terms rank higher.
  for (const [idx, h] of hits) {
    scores.set(idx, scores.get(idx) * (1 + 0.25 * (h - 1)));
  }

  // Chapter-contents (TOC) pages mention every topic but answer nothing — demote hard.
  // Glossary pages define everything but instruct nothing — demote moderately
  // (they should still win pure "what is X" definition queries).
  for (const [idx, sc] of scores) {
    const c = MANUAL_DATA.CHUNKS[idx];
    if (c.toc) scores.set(idx, sc * 0.2);
    else if (c.glo) scores.set(idx, sc * 0.55);
  }

  let candidates = [...scores.entries()].sort((a, b) => b[1] - a[1]).slice(0, 60);

  // Phrase-aware rescoring: reward chunks containing the query's actual
  // word pairs as phrases ("provisional ballot"), not just scattered words.
  const rawWords = (query.toLowerCase().match(/[a-z0-9]+/g) || []).filter(
    (w) => !STOP.has(stem(w))
  );
  const bigrams = [];
  for (let i = 0; i + 1 < rawWords.length; i++) {
    bigrams.push([rawWords[i], rawWords[i + 1]]);
  }
  if (bigrams.length || terms.length) {
    candidates = candidates.map(([idx, sc]) => {
      const c = MANUAL_DATA.CHUNKS[idx];
      const text = c.text.toLowerCase();
      const label = (c.label || "").toLowerCase();
      let phraseHits = 0;
      let labelPhrase = false;
      let headPhrase = false;
      const headline = text.slice(0, text.indexOf("\n") > 0 ? text.indexOf("\n") : 80);
      for (const [a, b] of bigrams) {
        // Match inflected forms too: "ballot procedure(s)"
        const re = new RegExp(stem(a) + "[a-z]*\\s+" + stem(b) + "[a-z]*");
        if (re.test(text)) phraseHits++;
        if (re.test(label)) labelPhrase = true;
        if (re.test(headline)) headPhrase = true;
      }
      let mult = 1 + 0.55 * Math.min(phraseHits, 3);
      // A section heading naming the query phrase IS the section on that topic.
      if (headPhrase) mult *= 1.5;
      // Label affinity: the chapter/section title naming a query concept is
      // the strongest topical signal in the manual.
      if (labelPhrase) mult *= 1.35;
      else if (terms.some((t) => label.includes(t))) mult *= 1.12;
      return [idx, sc * mult];
    });
    candidates.sort((a, b) => b[1] - a[1]);
  }

  // Exact-phrase boost on the raw query (2+ words).
  const phrase = query.trim().toLowerCase().replace(/[?.!,]/g, "");
  if (phrase.includes(" ")) {
    candidates = candidates.map(([idx, sc]) => {
      const text = D.CHUNKS[idx].text.toLowerCase();
      return [idx, text.includes(phrase) ? sc * 1.6 : sc];
    });
    candidates.sort((a, b) => b[1] - a[1]);
  }

  // Deduplicate by page: keep the best chunk per page. Then apply a quality
  // floor: only results in the same league as the best match get shown.
  const seenPages = new Set();
  const results = [];
  for (const [idx, sc] of candidates) {
    const c = MANUAL_DATA.CHUNKS[idx];
    if (seenPages.has(c.page)) continue;
    seenPages.add(c.page);
    results.push({ ...c, score: sc });
    if (results.length >= limit) break;
  }
  if (results.length > 1) {
    const top = results[0].score;
    const kept = results.filter((r) => r.score >= 0.4 * top);
    return { terms, results: kept };
  }
  return { terms, results };
}

/* ---------------- rendering ---------------- */

const $ = (sel) => document.querySelector(sel);

function escapeHtml(s) {
  return (s || "").replace(/[&<>'"]/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;",
  }[c]));
}

/* Highlight stemmed query terms inside an excerpt. */
function highlight(text, terms) {
  if (!terms.length) return escapeHtml(text);
  const safe = escapeHtml(text);
  const stems = new Set(terms);
  return safe.replace(/[A-Za-z0-9]+/g, (w) =>
    stems.has(stem(w.toLowerCase())) ? `<mark>${w}</mark>` : w
  );
}

/* Pick the most relevant window of a chunk for the excerpt. */
function excerpt(text, terms, maxLen = 420) {
  if (text.length <= maxLen) return text;
  const lower = text.toLowerCase();
  let bestPos = 0, bestScore = -1e9;
  const starts = [0];
  const re = /[.!?]\s+|\n(?=[A-Z•\d])/g;
  let m;
  while ((m = re.exec(text)) !== null) starts.push(m.index + m[0].length);
  for (const s of starts) {
    const windowText = lower.slice(s, s + maxLen);
    let count = 0;
    for (const t of terms) if (windowText.includes(t)) count++;
    // Penalize windows that are mostly stubby figure-label lines
    const lines = windowText.split("\n").filter((l) => l.trim());
    const stubby = lines.filter((l) => l.trim().split(/\s+/).length <= 2).length;
    const score = count * 3 - (lines.length ? (stubby / lines.length) * 4 : 0);
    if (score > bestScore) { bestScore = score; bestPos = s; }
  }
  let out = text.slice(bestPos, bestPos + maxLen);
  if (bestPos > 0) out = "…" + out;
  if (bestPos + maxLen < text.length) out += "…";
  return out;
}

function citationChip(r) {
  const tocTag = r.toc ? ' <em class="toc-tag">chapter contents</em>' : "";
  return `<span class="chip"><span class="chip-band"></span>${escapeHtml(r.label || "Manual")} · PDF p. ${r.page}${tocTag}</span>`;
}

function resultCard(r, terms, best = false) {
  return `
  <article class="card${best ? " best" : ""}">
    ${best ? '<div class="best-tag">Best match</div>' : ""}
    <div class="card-head">${citationChip(r)}</div>
    <div class="excerpt">${highlight(excerpt(r.text, terms), terms)}</div>
    <div class="card-actions">
      <button class="btn ghost" data-page="${r.page}">Read full page ${r.page}</button>
    </div>
  </article>`;
}

function renderResults(query) {
  const { terms, results } = search(query);
  const bestEl = $("#best");
  const moreEl = $("#more");
  const statusEl = $("#status");

  if (!results.length) {
    statusEl.textContent = "No matching sections found. Try different words — for example \u201Cprovisional ballot\u201D or \u201Cspoiled ballot\u201D.";
    bestEl.innerHTML = "";
    moreEl.innerHTML = "";
    return;
  }

  statusEl.textContent = `Found ${results.length} relevant section${results.length > 1 ? "s" : ""} for \u201C${query.trim()}\u201D`;
  bestEl.innerHTML = resultCard(results[0], terms, true);

  const rest = results.slice(1);
  moreEl.innerHTML = rest.length
    ? `<details><summary>More sections (${rest.length})</summary>${rest
        .map((r) => resultCard(r, terms))
        .join("")}</details>`
    : "";

  document.querySelectorAll("[data-page]").forEach((b) =>
    b.addEventListener("click", () => openPage(parseInt(b.dataset.page, 10), terms))
  );
}

/* ---------------- full-page viewer ---------------- */

let viewerPage = null;
let viewerTerms = [];

const PAGE_REF_JS = /^\s*\d{1,2}-\d{1,3}\s*$/;

/* TOC pages render as live links: topic lines run a search, page refs open pages. */
function renderTocBody(p, terms) {
  const lines = p.text.split("\n");
  const out = lines.map((ln) => {
    const s = ln.trim();
    if (!s) return "";
    if (PAGE_REF_JS.test(s)) {
      const target = MANUAL_DATA.LABELMAP[s];
      return target
        ? `<button class="toc-link ref" data-goto="${target}">${escapeHtml(s)} &rarr;</button>`
        : `<span class="toc-dead">${escapeHtml(s)}</span>`;
    }
    if (s.split(/\s+/).length >= 2) {
      return `<button class="toc-link" data-search="${escapeHtml(s)}">${highlight(s, terms)}</button>`;
    }
    return `<div>${highlight(s, terms)}</div>`;
  });
  return out.join("");
}

function openPage(page, terms = []) {
  viewerPage = page;
  viewerTerms = terms;
  const p = MANUAL_DATA.PAGES[String(page)];
  if (!p) return;
  $("#viewer-title").innerHTML = citationChip({ label: p.label, page, toc: p.toc });
  if (p.toc) {
    $("#viewer-body").innerHTML =
      '<p class="viewer-note">Chapter contents. Tap a topic to search it, or tap a page number to open that page.</p>' +
      renderTocBody(p, terms);
    document.querySelectorAll("#viewer-body .toc-link").forEach((b) =>
      b.addEventListener("click", () => {
        if (b.dataset.goto) {
          openPage(parseInt(b.dataset.goto, 10), viewerTerms);
        } else {
          $("#viewer").close();
          $("#q").value = b.dataset.search;
          renderResults(b.dataset.search);
          window.scrollTo({ top: 0 });
        }
      })
    );
  } else {
    const textHtml = highlight(p.text, terms).replace(/\n/g, "<br>");
    let html = "";
    if (p.deg === 1) {
      html += '<p class="viewer-note warn">This page reproduces a printed form or screenshots — automated text extraction is unreliable here. Refer to the page image below or the printed manual.</p>';
    } else if (p.deg === 2) {
      html += '<p class="viewer-note">Parts of this page (figures or screenshots) may not have extracted cleanly.</p>';
    }
    // Page image if the render script has produced one (jpg, then png)
    html += `<img class="page-img" id="pimg" alt="Manual page ${page}" src="img/p${page}.jpg" style="display:none">`;
    if (p.deg === 1) {
      html += `<details class="pg-text"><summary>Show extracted text</summary><div>${textHtml}</div></details>`;
    } else {
      html += `<div>${textHtml}</div>`;
    }
    $("#viewer-body").innerHTML = html;
    const im = $("#pimg");
    let triedPng = false;
    im.onload = () => { im.style.display = "block"; };
    im.onerror = () => {
      if (!triedPng) { triedPng = true; im.src = `img/p${page}.png`; }
      else {
        im.remove();
        // No image available for a form page: make the text visible after all
        const det = document.querySelector(".pg-text");
        if (det) det.open = true;
      }
    };
  }
  $("#viewer-prev").disabled = page <= MANUAL_DATA.MIN_PAGE;
  $("#viewer-next").disabled = page >= MANUAL_DATA.MAX_PAGE;
  $("#viewer").showModal();
  $("#viewer-body").scrollTop = 0;
}

/* ---------------- curated quick references ----------------
   Chips do NOT run live search: each maps to a hand-verified manual page,
   plus related pages. Deterministic, demo-safe. */

const CURATED = [
  { q: "Voter not found in the pollbook", page: 134, rel: [137, 106] },
  { q: "Provisional ballot procedures", page: 101, rel: [99, 105] },
  { q: "Spoiled ballot replacement", page: 85, rel: [87, 88] },
  { q: "Opening the polls", page: 173, rel: [118, 72] },
  { q: "Closing the polls", page: 67, rel: [204, 66] },
  { q: "Broken seal or tamper tape", page: 179, rel: [173, 68] },
  { q: "Voter needs assistance", page: 31, rel: [29, 32] },
  { q: "Electioneering rules", page: 35, rel: [36, 17] },
  { q: "Same day registration", page: 71, rel: [51, 72] },
  { q: "Voter in wrong precinct", page: 137, rel: [134, 106] },
];

function pageAsResult(page) {
  const p = MANUAL_DATA.PAGES[String(page)];
  return p ? { page, label: p.label, text: p.text, toc: p.toc, deg: p.deg } : null;
}

function renderCurated(topic) {
  const primary = pageAsResult(topic.page);
  if (!primary) return;
  $("#status").textContent = `Verified quick reference for \u201C${topic.q}\u201D \u2014 opens the manual at the procedure.`;
  const terms = tokenizeQuery(topic.q);
  $("#best").innerHTML = resultCard(primary, terms, true);
  const rel = topic.rel.map(pageAsResult).filter(Boolean);
  $("#more").innerHTML = rel.length
    ? `<details open><summary>Related pages (${rel.length})</summary>${rel
        .map((r) => resultCard(r, terms))
        .join("")}</details>`
    : "";
  document.querySelectorAll("[data-page]").forEach((b) =>
    b.addEventListener("click", () => openPage(parseInt(b.dataset.page, 10), terms))
  );
  openPage(topic.page, terms);
}

/* ---------------- wiring ---------------- */

document.addEventListener("DOMContentLoaded", () => {
  const q = $("#q");
  const run = () => {
    const query = q.value.trim();
    if (query) renderResults(query);
  };

  $("#searchBtn").addEventListener("click", run);
  q.addEventListener("keydown", (e) => {
    if (e.key === "Enter") { e.preventDefault(); run(); }
  });
  $("#clearBtn").addEventListener("click", () => {
    q.value = "";
    $("#status").textContent = "Ask a question to begin.";
    $("#best").innerHTML = "";
    $("#more").innerHTML = "";
    q.focus();
  });

  // Curated quick-reference chips (verified destinations, not live search)
  $("#topics").innerHTML = CURATED.map(
    (t, i) => `<button class="topic" data-i="${i}">${escapeHtml(t.q)}</button>`
  ).join("");
  document.querySelectorAll(".topic").forEach((b) =>
    b.addEventListener("click", () => renderCurated(CURATED[parseInt(b.dataset.i, 10)]))
  );

  // Viewer controls
  $("#viewer-close").addEventListener("click", () => $("#viewer").close());
  $("#viewer-prev").addEventListener("click", () => openPage(viewerPage - 1, viewerTerms));
  $("#viewer-next").addEventListener("click", () => openPage(viewerPage + 1, viewerTerms));
  $("#viewer").addEventListener("click", (e) => {
    if (e.target === $("#viewer")) $("#viewer").close();
  });

  // Voice input — graceful: hidden if unsupported.
  const SR = window.SpeechRecognition || window.webkitSpeechRecognition;
  const voiceBtn = $("#voiceBtn");
  if (!SR) {
    voiceBtn.hidden = true;
  } else {
    let rec = null;
    voiceBtn.addEventListener("click", () => {
      if (rec) { rec.stop(); return; }
      rec = new SR();
      rec.lang = "en-US";
      rec.interimResults = false;
      voiceBtn.classList.add("listening");
      voiceBtn.textContent = "Listening…";
      rec.onresult = (e) => {
        q.value = e.results[0][0].transcript;
        run();
      };
      rec.onerror = () => {
        $("#status").textContent = "Voice input isn\u2019t available right now (it may need this device\u2019s offline speech pack). Type your question instead.";
      };
      rec.onend = () => {
        voiceBtn.classList.remove("listening");
        voiceBtn.textContent = "\uD83C\uDFA4 Speak";
        rec = null;
      };
      rec.start();
    });
  }

  $("#pagecount").textContent = `${MANUAL_DATA.N} searchable sections · ${Object.keys(MANUAL_DATA.PAGES).length} manual pages`;
});
